### ISSUE TITLE
Examples fail to compile on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by ohz10** [MolecularMatters/raw_pdb#43]
Compiling examples on Ubuntu: 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

```
$ git log
commit c5308d53a66349f986e97c359a5a96ba12ee1003 (HEAD -> main, origin/main, origin/HEAD)
Merge: 3d876c8 dd0af39
Author: MolecularMatters <61518974+MolecularMatters@users.noreply.github.com>
Date:   Thu Dec 15 17:57:42 2022 +0100

    Merge pull request #40 from jeremyong/patch-1

    Resolve typo in GetModifierName
```

```
$ ninja
[1/2] Building CXX object src/Examples/CMakeFiles/Examples.dir/ExampleLines.cpp.o
FAILED: src/Examples/CMakeFiles/Examples.dir/ExampleLines.cpp.o
/usr/bin/c++  -I/home/user/proj/raw_pdb/src/. -O3 -DNDEBUG -std=gnu++11 -Winvalid-pch -include /home/user/proj/raw_pdb/build/src/Examples/CMakeFiles/Examples.dir/cmake_pch.hxx -MD -MT src/Examples/CMakeFiles/Examples.dir/ExampleLines.cpp.o -MF src/Examples/CMakeFiles/Examples.dir/ExampleLines.cpp.o.d -o src/Examples/CMakeFiles/Examples.dir/ExampleLines.cpp.o -c /home/user/proj/raw_pdb/src/Examples/ExampleLines.cpp
/home/user/proj/raw_pdb/src/Examples/ExampleLines.cpp: In function ‘void ExampleLines(const PDB::RawFile&, const PDB::DBIStream&, const PDB::InfoStream&)’:
/home/user/proj/raw_pdb/src/Examples/ExampleLines.cpp:183:38: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
  183 |                                 std::memcpy(line.checksum, checksumHeader->checksum, checksumHeader->checksumSize);
      |                                      ^~~~~~
      |                                      wmemcpy
ninja: build stopped: subcommand failed.
```

Adding `#include <cstring>` at the top of `ExampleLines.cpp` fixes the issue, but I was wondering if there's a more canonical place to put the include?

**Comment by tivolo** [comment]
Putting it directly into ExampleLines.cpp is fine, thanks!

**Comment by MolecularMatters** [comment]
Fixed in 8b3f87584950cdf1b11bb4e2f5985e09aac1cb78
